import test(...)
import assert

import callbackqueue

test("runs callback", () => {
  let result = mutable []

  let cbs = callbackqueue.new()
  cbs->add(() => {
    result->append("hello")
  })

  cbs->runAndClear()
  assert.equal(mutable ["hello"], result)

  cbs->runAndClear()
  assert.equal(mutable ["hello"], result)
})

test("runs all callbacks", () => {
  let result = mutable []

  let cbs = callbackqueue.new()
  cbs->add(() => {
    result->append("hello")
  })

  cbs->add(() => {
    result->append("goodbye")
  })

  cbs->runAndClear()

  assert.equal(["goodbye", "hello"], sorted(result->freeze()))
})

// possible exception modes:
//   exception stops execution, leaves queue empty
//   exception stops execution, leaves queue full
//   exception stops execution, next runAndClear() runs remainder
//   exception is caught, remainder runs, rethrown
//   exception is caught, remainder runs, not thrown
