let _throw: (a) -> b = _unsafe_js("function (e) { throw e; }")


fun throwAssertionFailure(message: String) {
    _throw("Assertion Failure: " + message)
}

export fun equal(expected, actual) {
    if expected != actual {
        throwAssertionFailure("expected " + toString(expected) + " but got " + toString(actual))
    }
}
